2024-05-28 17:48:29,973 - INFO - Will watch for changes in these directories: ['C:\\Users\\NAGARAJ\\dev\\agent-llm\\llm-langchain'][0m
2024-05-28 17:48:29,974 - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)[0m
2024-05-28 17:48:29,974 - INFO - Started reloader process [19440] using WatchFiles[0m
2024-05-28 17:48:32,202 - INFO - using chat provider: openai[0m
2024-05-28 17:48:32,588 - ERROR - Error: 'OPENAI_API_KEY'[0m
2024-05-28 17:48:32,653 - INFO - Started server process [9968][0m
2024-05-28 17:48:32,654 - INFO - Waiting for application startup.[0m
2024-05-28 17:48:32,670 - INFO - using embed provider: openai[0m
2024-05-28 17:48:32,686 - INFO - Application startup complete.[0m
2024-05-28 17:48:56,347 - WARNING - WatchFiles detected changes in 'agentbuilder\logger\custom_logging.py'. Reloading...[0m
2024-05-28 17:48:56,404 - INFO - Shutting down[0m
2024-05-28 17:48:56,514 - INFO - Waiting for application shutdown.[0m
2024-05-28 17:48:56,514 - INFO - Application shutdown complete.[0m
2024-05-28 17:48:56,515 - INFO - Finished server process [9968][0m
2024-05-28 17:48:59,040 - INFO - using chat provider: openai
2024-05-28 17:48:59,457 - ERROR - Error: 'OPENAI_API_KEY'
2024-05-28 17:48:59,514 - INFO - Started server process [18796]
2024-05-28 17:48:59,515 - INFO - Waiting for application startup.
2024-05-28 17:48:59,529 - INFO - using embed provider: openai
2024-05-28 17:48:59,550 - ERROR - Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\NAGARAJ\dev\agent-llm\llm-langchain\venv\Lib\site-packages\uvicorn\server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "C:\Users\NAGARAJ\dev\agent-llm\llm-langchain\venv\Lib\site-packages\uvicorn\server.py", line 89, in startup
    await self.lifespan.startup()
  File "C:\Users\NAGARAJ\dev\agent-llm\llm-langchain\venv\Lib\site-packages\uvicorn\lifespan\on.py", line 54, in startup
    await self.startup_event.wait()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NAGARAJ\dev\agent-llm\llm-langchain\venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "C:\Users\NAGARAJ\dev\agent-llm\llm-langchain\venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-05-28 17:48:59,783 - INFO - Stopping reloader process [19440][0m
2024-05-28 17:49:01,040 - INFO - Will watch for changes in these directories: ['C:\\Users\\NAGARAJ\\dev\\agent-llm\\llm-langchain']
2024-05-28 17:49:01,041 - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2024-05-28 17:49:01,042 - INFO - Started reloader process [10736] using WatchFiles
2024-05-28 17:49:03,678 - INFO - using chat provider: openai
2024-05-28 17:49:04,116 - ERROR - Error: 'OPENAI_API_KEY'
2024-05-28 17:49:04,174 - INFO - Started server process [36188]
2024-05-28 17:49:04,174 - INFO - Waiting for application startup.
2024-05-28 17:49:04,188 - INFO - using embed provider: openai
2024-05-28 17:49:04,206 - INFO - Application startup complete.
2024-05-28 17:49:10,868 - WARNING - WatchFiles detected changes in 'agentbuilder\logger\custom_logging.py'. Reloading...
2024-05-28 17:49:10,983 - INFO - Shutting down
2024-05-28 17:49:11,093 - INFO - Waiting for application shutdown.
2024-05-28 17:49:11,094 - INFO - Application shutdown complete.
2024-05-28 17:49:11,096 - INFO - Finished server process [36188]
2024-05-28 17:49:13,890 - INFO - using chat provider: openai
2024-05-28 17:49:14,278 - ERROR - Error: 'OPENAI_API_KEY'
2024-05-28 17:49:14,336 - INFO - Started server process [36644]
2024-05-28 17:49:14,337 - INFO - Waiting for application startup.
2024-05-28 17:49:14,348 - INFO - using embed provider: openai
2024-05-28 17:49:14,366 - INFO - Application startup complete.
2024-05-28 17:49:23,428 - INFO - Shutting down
2024-05-28 17:49:23,536 - INFO - Waiting for application shutdown.
2024-05-28 17:49:23,536 - INFO - Application shutdown complete.
2024-05-28 17:49:23,537 - INFO - Finished server process [36644]
2024-05-28 17:49:23,769 - INFO - Stopping reloader process [10736]
